name: Java CI with Maven

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ] 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # 1. Code auschecken

    # 2. JDK Setup: Setzt JDK 21 last LTS
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21' 
        distribution: 'temurin'
        cache: maven 

    # 3. Haupt-Build & Statische Analyse (OHNE IMAGE BUILD)
    # Wir nutzen 'verify' anstelle von 'install', um zu kompilieren, Tests auszuf端hren 
    # und Plugins wie den Enforcer zu triggern, ohne den letzten Schritt des Image-Baus.
    - name: Maven Build, Verify & Site Generation
      run: |
        # F端hrt Kompilierung, statische Analysen (Enforcer) und Tests aus (falls aktiviert)
        # Wenn Sie sicher sind, dass Tests 端bersprungen werden sollen (wie im Meilenstein gefordert):
        mvn -B verify -D'maven.test.skip=true' --file pom.xml
        
        # Generiert die Berichte f端r Checkstyle, PMD und SpotBugs
        mvn site -D'maven.test.skip=true' --file pom.xml

    # 4. Optional: Hochladen des statischen Analyseberichts
    - name: Upload Site Reports Artifact
      uses: actions/upload-artifact@v4
      with:
        name: maven-site-reports
        path: target/site/

    # Optional: Uploads the full dependency graph...
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
