' Copyright (C) 2019 - present Juergen Zimmermann, Hochschule Karlsruhe
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <https://www.gnu.org/licenses/>.
@startuml KundeController

skinparam classAttributeIconSize 0

package org.springframework {
    package web.bind.annotation {
        annotation RestController
        annotation RequestMapping
        annotation PathVariable
        annotation RequestParam
        annotation ExceptionHandler
        annotation ResponseStatus
    }

    package http {
        class ResponseEntity<T>
    }
    package util {
        class MultiValueMap<K,V>
    }
}

package java.util {
    interface Collection
    class UUID
}

package com.acme.kunde {
    package entity {
        class Kunde
    }
    package service {
        class KundeService << control >> << @Service >>

        ' TODO Gradle: "exception" wird erst AsciiDoctor_plugin 5.x unterstuetzt
        exception NotFoundException

        KundeService .right[hidden].> Kunde
    }

    package rest #DDDDDD {
        class KundeController << boundary >> << @RestController >> << @RequestMapping >> {
            ~ @GetMapping getById(@PathVariable id: UUID): Kunde
            ~ @GetMapping get(@RequestParam queryParams: MultiValueMap<String, String>): Collection<Kunde>
        }

        class GlobalExceptionHandler << @ControllerAdvice >> {
            ~ @ExceptionHandler @ResponseStatus onNotFound(ex: NotFoundException)
        }

        KundeController o--> "1" KundeService : service

        KundeController .up.> RestController
        KundeController .up.> RequestMapping
        KundeController .up.> PathVariable
        KundeController .up.> RequestParam
        KundeController .up.> ResponseEntity
        KundeController .up.> MultiValueMap
        KundeController .down.> Kunde

        GlobalExceptionHandler .up.> ExceptionHandler
        GlobalExceptionHandler .up.> ResponseStatus
        GlobalExceptionHandler ..> NotFoundException

        KundeController .right.> UUID
        KundeController ..> Collection
    }
}

hide empty members

footer (c) Juergen Zimmermann

@enduml
